name: Deploy to Prod

on:
  push:
    branches:
      - main

env:
  TOKEN_PERSONAL: ${{ secrets.TOKEN_PERSONAL }}
  GITHUB_TOKEN: ${{ secrets.TOKEN_PERSONAL }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Push force to env-prod branch
        run: |
          echo $TOKEN_PERSONAL
          git config --global user.email "13791385+omariosouto@users.noreply.github.com"
          git config --global user.name "Mario Souto [BOT]"
          git checkout -b env-prod
          git merge main
          git push -u origin env-prod

# git reset --hard main