name: Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Push force to env-prod branch
        run: |
          echo $TOKEN_PERSONAL
          git config --global user.email "13791385+omariosouto@users.noreply.github.com"
          git config --global user.name "Mario Souto [BOT]"
          git checkout -b env-prod
          git merge main
          git push origin env-prod --force

# git reset --hard main